# This is a config for E2B sandbox template.
# You can use template ID (sf0n8ryku4nu34gdqa0s) or template name (ship0-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ship0-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("ship0-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ship0-nextjs')

team_id = "240f6af1-0762-4bf9-a6dc-9ec61beaffb9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ship0-nextjs"
template_id = "sf0n8ryku4nu34gdqa0s"
